import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
selenium_ruby = driver.find_element_by_css_selector(".text-22-sub_row_1-0-2-0-0")
selenium_ruby.click()
time.sleep(3)
review = driver.find_element_by_class_name("reviews_tab")
review.click()
time.sleep(3)
rating = driver.find_element_by_class_name("star-5")
rating.click()
time.sleep(3)
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice book!")
time.sleep(3)
name = driver.find_element_by_id("author")
name.send_keys("Sergio")
time.sleep(3)
email = driver.find_element_by_id("email")
email.send_keys("sergio_chachez@gmail.com")
time.sleep(3)
submit_btn = driver.find_element_by_id("submit")
submit_btn.click()
time.sleep(3)
driver.quit()

